name: Deploy to Production

# Definir os gatilhos para o workflow
on:
  push:
    branches:
      - main  # Ou qualquer outra branch que deseja monitorar

# Configuração das jobs do workflow
jobs:
  deploy:
    runs-on: ubuntu-latest  # Executa em uma máquina Ubuntu

    steps:
    # 1. Checar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar Node.js (Exemplo de aplicação Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ou qualquer versão necessária para o seu app

    # 3. Instalar dependências
    - name: Install dependencies
      run: npm install

    # 4. Rodar os testes (Opcional, pode ser removido se não for necessário)
    - name: Run tests
      run: npm test

    # 5. Criar os artefatos ou build (depende da aplicação)
    - name: Build the application
      run: npm run build

    # 6. Fazer o deploy
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.0  # Action para SSH
      with:
        host: ${{ secrets.HOST }}  # Defina isso no repositório em Secrets
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Defina a chave SSH no Secrets
        port: 22
        script: |
          cd /path/to/your/app
          git pull origin main  # Ou outro comando para atualizar o código
          npm install
          pm2 restart app  # Exemplo para reiniciar a aplicação Node.js com PM2

